# Generated by Django 4.1.7 on 2023-03-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producthighlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated']},
        ),
    ]
