GET http://127.0.0.1:8000/products/1
Accept: application/json

###

PATCH http://127.0.0.1:8000/products/1
Content-Type: application/json

{"stock": 10, "price": 4}

###

PATCH http://127.0.0.1:8000/products/MY-0001
Content-Type: application/json

{"id": 2}

###

DELETE http://127.0.0.1:8000/products/MY-0001
