GET http://127.0.0.1:8000/sessions/
Accept: application/json

###

POST http://127.0.0.1:8000/sessions/
Content-Type: application/json

{
  "data": {
    "username": "admin",
    "password": "admin"
  }
}

###

DELETE http://127.0.0.1:8000/sessions/
